### ISSUE TITLE
Hooks "on_env" not working

### ISSUE THREAD

**Issue by stonebuzz** [aklajnert/mkdocs-simple-hooks#29]
Hello,

first of all thank you for this plugin, to extend ```mkdocs``` features without having to create a new package.   :smiley:

I have problem about the implementation of  ```on_env``` hook to add a my own ```jinja2``` filter .

There is my ```mkdocs.yml``` configuration : 

```yaml
plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_env: "docs.hooks:on_env"
```

The contents of the file ```docs/hooks.py```

```python
def say_hello(s:str):
    return "<i>Hello %s</i>" % s

def on_env(env, config, files, **kwargs):
    env.filters['say_hello'] = say_hello
    return env
```

From a ```jinja2``` template the new filter is called like this

```twig
{{nav_item.title|say_hello}}
```
After running ```mkdocs``` command (```mkdocs serve```) I get the following error

```
jinja2.exceptions.TemplateAssertionError: No filter named 'say_hello'.
```

Complete ```stacktrace```
```
INFO     -  Building documentation...
INFO     -  Cleaning site directory
Traceback (most recent call last):
  File "/home/user/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 83, in serve
    builder(config)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 320, in build
    _build_theme_template(template, env, files, config, nav)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 118, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/home/user/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 97, in _build_template
    output = template.render(context)
  File "/home/user/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/user/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/.local/lib/python3.10/site-packages/material/404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "/home/user/.local/lib/python3.10/site-packages/material/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/home/user/.local/lib/python3.10/site-packages/material/base.html", line 148, in top-level template code
    {% block site_nav %}
  File "/home/user/.local/lib/python3.10/site-packages/material/base.html", line 156, in block 'site_nav'
    {% include "partials/nav.html" %}
  File "/home/user/.local/lib/python3.10/site-packages/material/partials/nav.html", line 27, in top-level template code
    {% include "partials/nav-item.html" %}
  File "/home/user/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/dev/faq/overrides/partials/nav-item.html", line 32, in template
    {{nav_item.title|say_hello}}
jinja2.exceptions.TemplateAssertionError: No filter named 'say_hello'.
```

If i change ```mkdocs.yml``` like this

```yaml
plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_env: "docs.hook:on_env"  # 'hook' instead of 'hooks'
```
I get the following warning

```
WARNING  -  Config value 'plugins': Plugin 'mkdocs-simple-hooks': Cannot import module 'docs.hook'.
```

I conclude that the original configuration file is correct and that it correctly loads the ```docs/hooks.py``` file

The declaration of  ```on_env``` hook seems correct if I follow the docs from  ```Mkdocs``` and ```jinja2```
https://www.mkdocs.org/dev-guide/plugins/#on_env
https://jinja.palletsprojects.com/en/latest/api/#custom-filters

I don't understand where the problem lies (python declaration ?)

My ```Mkdocs``` setup information

```mkdocs``` ```1.1.2```
```mkdocs-material``` ```5.4.0```
```mkdocs-simple-hooks``` ```0.1.5```
```mkdocs-static-i18n``` ```0.53```

Best regards

**Comment by aklajnert** [comment]
Hi @stonebuzz - this plugin is actually kind of deprecated since Mkdocs 1.4. If you can, please upgrade and see [the docs](https://www.mkdocs.org/user-guide/configuration/#hooks). If the problem still exists, I think it will be better to raise this issue for the official mkdocs than here, as it will benefit more people.

**Comment by stonebuzz** [comment]
Hi @aklajnert 
thanks for your quick response 
Indeed I had not paid attention to this new feature.

The problem seems to persist with this new way of doing things

I opened an issue from the official mkdocs.

Best regards

**Comment by thesuperzapper** [comment]
@stonebuzz I would greatly appreciate you updating the readme with a link to the [MkDocs `hooks` feature](https://www.mkdocs.org/user-guide/configuration/#hooks), with a message saying that the plugin is no longer needed.

Either way, thanks for your previous work!
